const form_projects = {
  GET_PROJECTS: "GET_PROJECTS",
  LOADING_GET_PROJECTS: "LOADING_GET_PROJECTS",
  SUCCESS_GET_PROJECTS: "SUCCESS_GET_PROJECTS",
  FAIL_GET_PROJECTS: "FAIL_GET_PROJECTS",
};

export default form_projects;